gText_Birch_Welcome:: .string "Hola! Perdon por la espera!\p" .string
"Bienvenido al mundo de POKeMON!\p" .string "Mi nombre es OAK.\p" .string "La
gente me llama el PROFESOR\n" .string "POKeMON.\p" .string "$"
gText_Birch_Pokemon:: .string "A esto le llamamos un POKeMON.\p" .string "\n"
.string "$" gText_Birch_MainSpeech:: .string "Este mundo esta habitado por\n"
.string "criaturas conocidas como POKeMON.\p" .string "La gente y los POKeMON
viven juntos,\n" .string "apoyandose mutuamente.\p" .string "Algunos juegan con
POKeMON,\n" .string "otros pelean con ellos. \p" .string "Pero aun no lo sabemos
todo sobre\n" .string "los POKeMON. \p" .string "Todavia hay muchos misterios\n"
.string "por resolver. Por eso estudio\l" .string "POKeMON todos los dias.\p"
.string "$" gText_Birch_AndYouAre:: .string "Y tu eres?$"
gText_Birch_BoyOrGirl:: .string "Eres un chico?\n" .string "O eres una chica?$"
gText_Birch_Difficulty:: .string "Aha…\p" .string "Y… Como crees que sera
esta\n" .string "aventura?$" gText_Birch_LockDifficulty:: .string "Si necesitas
cambiar la DIFICULTAD\n" .string "puedes abrir el MENU de OPCIONES y\l" .string
"cambiarla desde ahi.\p" .string "Tambien puedes bloquearla, si quieres.\n"
.string "Quieres bloquear la\l" .string "DIFICULTAD elegida?\p" .string "Esto no
se puede cambiar despues.$" gText_Birch_Challenge:: .string "Oh, es asi?\p"
.string "Muy bien, con eso claro…\n" .string "Esperas algun DESAFIO\l" .string
"en tu viaje?\p" .string "Y cual es tu nombre?$" gText_Birch_WhatsYourName::
.string "Ahora, como dijiste que te\n" .string "llamabas?$"
gText_Birch_SoItsPlayer:: .string "Oh! Asi que eres {PLAYER}{KUN}?$"
gText_Birch_YourePlayer:: .string "{PLAYER}{KUN}, estas listo?\p" .string "Tu
propia aventura esta a punto\n" .string "de comenzar.\p" .string "$"
gText_Birch_AreYouReady:: .string "Enfrentaras momentos divertidos\n" .string "y
desafios dificiles.\p" .string "Un mundo de sueños y aventuras\n" .string "con
POKeMON te espera! Vamos!\p" .string "Te vere mas tarde!\p" .string "$"
