gText_ObtainedTheItem:: .string "Has obtenido {STR_VAR_2}!$"
gText_TheBagIsFull:: .string "La MOCHILA esta llena…$" gText_PutItemInPocket::
.string "{PLAYER} guardo {STR_VAR_2}\n" .string "en el BOLSILLO {STR_VAR_3}.$"
gText_PlayerFoundOneItem:: .string "{PLAYER} encontro un {STR_VAR_2}!$"
gText_TooBadBagIsFull:: .string "Que pena!\n" .string "La MOCHILA esta llena…$"
gText_PlayerPutItemInBag:: .string "{PLAYER} guardo {STR_VAR_2}\n" .string "en
la MOCHILA.$" gText_ObtainedTheDecor:: .string "Has obtenido {STR_VAR_2}!$"
gText_NoRoomLeftForAnother:: .string "Que pena! No hay espacio para\n" .string
"otro {STR_VAR_2}…$" gText_TheDecorWasTransferredToThePC:: .string "{STR_VAR_2}
fue transferido\n" .string "al PC.$" gText_PutItemInPC:: .string "{PLAYER}
guardo {STR_VAR_2}\n" .string "en el PC porque la mochila esta llena.$"
gText_TooBadBagAndPCAreFull:: .string "Que pena!\n" .string "La MOCHILA y el PC
estan llenos…$"
