gText_WouldYouLikeToRestYourPkmn:: .string "Hola, bienvenido al\n" .string
"CENTRO POKeMON.\p" .string "Restauramos a tus POKeMON\n" .string "cansados a
plena salud.\p" .string "Quieres curar a tus POKeMON?$" gText_IllTakeYourPkmn::
.string "Muy bien, cuidare de tus POKeMON\n" .string "unos segundos.$"
gText_RestoredPkmnToFullHealth:: .string "Gracias por esperar.\p" .string "Hemos
restaurado a tus POKeMON\n" .string "a plena salud.$"
gText_WeHopeToSeeYouAgain:: .string "Esperamos verte de nuevo!$"
gText_WelcomeCutShort:: .string "Hola, bienvenido al\n" .string "CENTRO
POKeMON.\p" .string "Restauramos a tus POKeMON\n" .string "cansados a plena
salud.\p" .string "Quieres…$" gText_NoticesGoldCard:: .string "Es-esa
tarjeta…\n" .string "Podria ser… La TARJETA DORADA?!\p" .string "Oh, el color
dorado es brillante!\n" .string "Las cuatro estrellas parecen brillar!\p"
.string "He visto varios ENTRENADORES con\n" .string "una TARJETA PLATEADA
antes, pero, {PLAYER},\l" .string "eres el primer ENTRENADOR que veo\l" .string
"con una TARJETA DORADA!\p" .string "Muy bien, {PLAYER}, permiteme\n" .string
"el honor de curar a tus POKeMON!$" gText_YouWantTheUsual:: .string "Estoy
encantada de verte, {PLAYER}!\n" .string "Quieres lo de siempre, verdad?$"
gText_IllTakeYourPkmn2:: .string "Muy bien, cuidare de tus POKeMON\n" .string
"unos segundos.$" gText_ThankYouForWaiting:: .string "Gracias por esperar.$"
gText_WeHopeToSeeYouAgain2:: .string "Esperamos verte de nuevo!$"
gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge .string "Lo
siento, estas jugando con\n" .string "el desafio CENTRO POKeMON!\p" .string
"Buena suerte!{PAUSE_UNTIL_PRESS}$"
