.align 2 gText_ConfirmSave:: .string "Quieres guardar la partida?$"
gText_AlreadySavedFile:: .string "Ya hay una partida guardada.\n" .string
"Quieres sobreescribirla?$" gText_SavingDontTurnOff:: .string "GUARDANDO…\n"
.string "NO APAGUES LA CONSOLA.$" gText_PlayerSavedGame:: .string "{PLAYER}
guardo la partida.$" gText_DifferentSaveFile:: .string "ATENCION!\p" .string
"Hay una partida diferente\n" .string "ya guardada.\p" .string "Si guardas
ahora, la aventura\n" .string "del otro archivo, incluyendo objetos y\l" .string
"POKeMON, se perdera por completo.\p" .string "Seguro que quieres guardar
ahora\n" .string "y sobreescribir el otro archivo?$" gText_SaveError:: .string
"Error al guardar.\p" .string "Por favor cambia la\n" .string "memoria de
respaldo.$" gText_SavingDontTurnOffPower:: .string "GUARDANDO…\n" .string "NO
APAGUES LA CONSOLA.$"
